name: login_shop
description: A Flutter authentication app with SQLite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.5 # Versión compatible sugerida
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  image_picker: ^1.0.0
  mailer: ^6.0.1
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
